name: JMA Cloud Generator

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install system deps (canvas)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libcairo2-dev \
            libpango1.0-dev \
            libjpeg-dev \
            libgif-dev \
            librsvg2-dev

      - name: Install npm deps
        run: npm install

      - name: Run generator
        run: node js/JMA_cloudsGenerate.js
