name: Daily XREA Trigger

on:
  workflow_dispatch:
  schedule:
    - cron: "5 15 * * *"
    - cron: "10 19 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Call PHP
        run: |
          TS=$(date +%s)
          SECRET=${{ secrets.XREA_SECRET }}
          SIG=$(echo -n "$TS+$SECRET" | sha256sum | awk '{print $1}')
          curl -v "${{ secrets.XREA_URL }}?ts=$TS&sig=$SIG"
# refresh
