name: KANTO Whether Control

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run KANTO Control
        run: |
          node js/KANTO_control.js

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data/*.csv || true
          git diff --cached --quiet && echo "No changes" && exit 0
          git commit -m "update whether csv"
          git push
