name: KANTO Load CSV

on:
  workflow_dispatch:   # 手動実行用
  schedule:
    - cron: '0 16 * * *'
    - cron: '0 17 * * *' # 1:00 JST（テスト後そのまま運用可）
    - cron: '0 18 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch API
        run: |
          mkdir -p data

          echo "Fetching..."

          curl -s "https://turiiko.shop/actions/KANTO/load.php" \
            -H "Accept: application/json" \
            -o data/KANTO_load.json

          echo "Result:"
          cat data/KANTO_load.json

      - name: Commit result
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/KANTO_load.json

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "test: update kanto load"
          git push
