name: Remove IC from JSON

on:
  workflow_dispatch: # 管理画面からの手動実行用トリガー

jobs:
  remove-ic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run script to remove IC
        run: node remove_ic.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Chore: 既存のJSONからICデータを削除"
          git push
