name: Weather Batch

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # 1時間ごと

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        region: [KANTO] # 必要なら増やす

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install node-fetch

      - name: Run script
        run: node testNode.js
        env:
          REGION: ${{ matrix.region }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/*.csv || true
          git commit -m "update weather data" || echo "no changes"
          git push
