name: Update News JSON

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ❌ これ削除
      # - name: Enable ES Modules
      #   run: echo '{"type":"module"}' > package.json

      # ここでちゃんと全部入る
      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node js/newsNode.js

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add data/news.json

          git diff --cached --quiet || git commit -m "update news json"
          git push
